// wordStorage.js

var wordStorage = {
    'não': 'not',
    'olá': 'Noot Nooot',
    'gosto': 'NotNotNoot',
    'pão': 'Not Noot Nooot',
    'pneumoultramicroscopicossilicovulcanoconiótico': 'NoooooootNootNoooooootNooootNotNooooooootNoootNotNoootNootnooooot',
    'macarrão': 'Notnonnõo',
    'cachorro': 'NootNootNoot',
    'sol': 'NootNoot',
    'feliz': 'NootNooot',
    'teste': 'Nooot',
    'penis': 'no',
    'rola': 'no',
    'genitalia': 'no',
    'pinto': 'no',
    'Legal': 'noot notnoot',
    'λοπαδο­τεμαχο­σελαχο­γαλεο­κρανιο­λειψανο­δριμ­υπο­τριμματο­σιλφιο­καραβο­μελιτο­κατακεχυ­μενο­κιχλ­επι­κοσσυφο­φαττο­περιστερ­αλεκτρυον­οπτο­κεφαλλιο­κιγκλο­πελειο­λαγῳο­σιραιο­βαφη­τραγανο­πτερύγων': 'Noo Noot',
    'abacaxi': 'Noo NootNooot',
    'computador': 'Nooot Noot Nooot',
    'montanha': 'NootNootNootNoot Noot',
    'viagem': 'NootNo',
    'algoritmo': 'Noot Nooot No Nooot',
    'inspiração': 'Noot NootNoot NoootNoot',
    'oceano': 'NootNoot Noot Nooot',
    'fotografia': 'Not NoootNoot Nooot',
    'alegria': 'NootNooot No Noot',
    'aventura': 'NootNoot NootNoot Noot',
    'girafa': 'Noot NootNoot Noot',
    'melodia': 'NotNo NootNootNoot',
    'paralelepípedo': 'NootNootNootNoot Noot',
    'poliglota': 'NootNoootNootNo Noot',
    'radiante': 'NootNootNoot Noot',
    'pingui': 'Noooot',
    'translator': 'NonotNoot',
    'banana': 'Nototo',
    'felps': 'Felnoot',
    'sigma': 'uma raça maluca de pessoas homens',
    // Adicione mais palavras conforme necessário.
};
